### ISSUE TITLE
Allow someone to be entered to multiple committees

### ISSUE THREAD

**Issue by grantg012** [PurdueIEEE/dues#3]

**Comment by hadiahmed098** [comment]
This should not be too hard to do from a website perspective, but is there anything from a database perspective that might affect this? Would this break the search on `view.php`?

**Comment by grantg012** [comment]
The search in `view.php` is just a basic text search so it should be fine. I think the database change we'll need to make is to manually edit people that are in multiple committees but only listed as one.
